export enum Colors {
  SOFT_PEACH = '#FED6BC',
  LIGHT_GREEN = '#C3FBD8',
  PASTEL_SKY = '#DEF7FE',
  LIGHT_PURPLE = '#E7ECFF',
  LIGHT_YELLOW = '#FFFADD',
  PINK = '#FFC0CB',
  LIIGHT_PINK = '#FDEED9',
  AQUAMARINE = '#B5F2EA',
  LILAC = '#C6D8FF',
}